name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Reemplaza con el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .  # Apunta a la raíz del repositorio donde están tus archivos

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Asegúrate de que el GITHUB_TOKEN tiene los permisos correctos
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Apunta a la raíz del directorio donde están tus archivos
