name: Deploy JAS Music Records Official

on:
  push:
    branches:
      - acciones  # Asegúrate de cambiar "main" a "acciones" para que el flujo de trabajo se ejecute en esta rama

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ./public  # Asegúrate de que esta ruta apunte al directorio correcto donde se encuentran tus archivos construidos

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

